In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import  SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import  accuracy_score,classification_report

In [3]:
data=pd.read_csv("../datasets/sonar.csv",header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
data.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [5]:
x=data.drop(columns=[60],axis=1)
y=data[60]

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,stratify=y,random_state=0,shuffle=True)

In [11]:
model = make_pipeline(StandardScaler(), SVC())
model=model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'R', 'R', 'M',
       'R', 'R', 'M', 'R', 'M', 'R', 'R', 'M', 'M', 'R', 'M', 'M', 'M',
       'R', 'M', 'M', 'M', 'R', 'M', 'M', 'M', 'R', 'M', 'R', 'M', 'R',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'R', 'M', 'M', 'R', 'M', 'R'],
      dtype=object)

In [12]:
accuracy_score(y_pred,y_test)

0.8846153846153846

In [13]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           M       0.93      0.87      0.90        30
           R       0.83      0.91      0.87        22

    accuracy                           0.88        52
   macro avg       0.88      0.89      0.88        52
weighted avg       0.89      0.88      0.89        52